config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'

  resource :user, except: [:new]
  resolve('User') { [:user] }
  get '/users/all', to: 'users#index_users'
  get '/user/friends', to: 'users#index_friends'
  delete '/user/friends', to: 'users#remove_friend'
  post '/users/all', to: 'users#add_friend'

  #resources :sessions, only: [:create, :destroy]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get '/sessions/user', to: 'devise/sessions#create', via: :post
  end

  get '/sessions/user', to: 'devise/sessions#create', via: :post
  

  #get 'signup', to: 'users#new', as: 'signup'
  #get 'login', to: 'pages#login', as: 'login'
  #get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :categories

  get '/categories/users/fav_categories', to:'categories#fav_categories', as: 'fav_categories'
  post '/categories/users/fav_categories', to:'categories#create_fav_categories', as: 'create_fav_categories'

  resources :locations
  
  get '/locations/add_favloc/:id', to: 'locations#addto_favloc', as: 'add_favloc'
  get '/users/locations', to: 'locations#index_favloc', as: 'index_favloc'
  delete '/locations/delete_favloc/:id', to: 'locations#deletefrom_favloc', as: 'delete_favloc'

  
  resources :gatherings

  #generazione e modifica della location
  post '/gatherings/new/generate_locations', to: 'gatherings#generate_locations'
  post '/gatherings/edit/update_location', to: 'gatherings#update_location'


  get '/accept', to: 'locations#accept'
  post '/accept', to: 'locations#accept_locations'

  get '/index_admin', to: 'locations#index_admin'

  


end

app/models/user.rb
require 'rubygems'
require 'role_model'

class User < ApplicationRecord
  include RoleModel
    ROLES = %w[user owner].freeze
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  # caratteristiche di ogni utente iscritto a WhereNext:
  # autenticabili attraverso l'uso del database (la loro identità digitale
  # verrà salvata dentro il database), i loro attributi potranno essere recuperati (:recoverable), 
  # l'utente potrà clicare su "ricordami" per non dover farel'autenticazione tutte le volte (:rememberable), etc..
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, 
         :omniauth_providers => [:facebook] 

    #has_secure_password
    validates :email, presence: true, uniqueness: true

    PASSWORD_REQUIREMENTS= /\A
        (?=.{8,}) # Almeno 8 caratteri
        (?=.*\d) # Almeno un numero
        (?=.*[A-Z]) # Almeno un carattere maiuscolo
        (?=.*[[:^alnum:]]) # Almeno un simbolo
    /x

    validates :password, presence: true, format:PASSWORD_REQUIREMENTS, :if => :password
    
    has_many :fav_locations, dependent: :destroy
    has_many :locations, :through => :fav_locations, :dependent => :destroy

    has_many :my_locations, :class_name => "Location"

    has_many :fav_categories, dependent: :destroy
    has_many :categories, :through => :fav_categories, :dependent => :destroy

    has_many :friendships, dependent: :destroy
    has_many :friends, :through => :friendships

    has_many :groups, dependent: :destroy
    has_many :gatherings, :through => :groups


    roles :admin, :owner, :user

    acts_as_user :roles=> [:user, :owner, :admin]

    def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
            user.email = auth.info.email
            user.password = Devise.friendly_token[0,20]
            user.avatar = auth.info.image
            user.name = auth.info.name
            user.roles_mask = 1
        end
    end
    
    def self.new_with_session(params, session)
        super.tap do |user|
            if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
            user.email = data["email"] if user.email.blank?
            end
        end
    end 
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
        def facebook
        # You need to implement the method below in your model (e.g. app/models/user.rb)
            @user = User.from_omniauth(request.env["omniauth.auth"])
            if @user.persisted?
                sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
                set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
            else
                session["devise.facebook_data"] = request.env["omniauth.auth"]
                redirect_to new_user_registration_path
            end
        end

        def failure
            redirect_to root_path
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!, except: [:new, :create]
    def show
    end

    def edit
    end

    def update
        new_user=current_user.update(params.require(:user).permit(:name,:email,:avatar))
        redirect_to root_path
    end

    def index_friends
        @friends=current_user.friends
    end

    def index_users
        @users= User.where.not(id: current_user.friends) #TODO fai vedere solo quelli con ruolo user
    end
    
    def add_friend
        new_friend=User.find(params[:id])
        if(!current_user.friends.include? new_friend)
            current_user.friends<<new_friend
            new_friend.friends<<current_user
            redirect_to user_friends_path
        else
            redirect_to user_all_path
        end
    end

    def remove_friend
        rem_friend=User.find(params[:id])
        if(current_user.friends.include? rem_friend)
            current_user.friends.delete(rem_friend)
            rem_friend.friends.delete(current_user)
        end
        redirect_to user_friends_path
    end

    def destroy
        curr_user_id=current_user.id
        id_rmv=params[:id]
        User.destroy(id_rmv)
        if (id_rmv==curr_user_id)
            redirect_to root_path
        else
            redirect_to users_all_path
        end
    end

    

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="image_cover">
    <%= image_tag  "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Casa_Classic_Cocktail_Bar_%26_Jazz_Club_by_Roland_Barrera.jpg/1280px-Casa_Classic_Cocktail_Bar_%26_Jazz_Club_by_Roland_Barrera.jpg" %>
</div>
<div class="user_info">
  <h1>Edit</h1>
  <%= form_with model: current_user, method:"PUT" do |f| %>
    <div>
      Nome: <%= f.text_field :name  %>
    </div>
    <div>
      Email: <%= f.email_field :email %>
    </div>
    <div>
      Avatar url: <%= f.text_field :avatar %>
    </div>
    <div>
      <%= f.submit "Edit" , class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/users/index_friends.html.erb
<div class="image_cover">
    <%= image_tag  "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Casa_Classic_Cocktail_Bar_%26_Jazz_Club_by_Roland_Barrera.jpg/1280px-Casa_Classic_Cocktail_Bar_%26_Jazz_Club_by_Roland_Barrera.jpg" %>
</div>
<div class="table-scroll">
    <h1> Your friends </h1>
    <%if @friends.length>0%>
        <div class="table-conteiner">
        <table class="table">
            <thead>
                <th colspan="1"></th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th colspan="3"></th>
                </th>
            </thead>
            <tbody>
                <% @friends.each do |user|%>
                    <%if user!=current_user%>
                        <tr>
                            <td><% if user.avatar && user.avatar!="" %> 
                                    <%= image_tag  user.avatar %>
                                <% else %>
                                    <%= image_tag  "no-profile-picture.jpg" %>
                                <% end %>
                            </td>
                            <td><%= user.name %></td>
                            <td><%= user.email %> &nbsp;</td>
                            <td><%= link_to  "Remove", user_friends_path(id: user.id),method:"delete" %>&nbsp;</td>
                        </tr>
                    <%end%>
                <% end %>
            </tbody>
        </table>
        </div>
    <%else%>
        <h5> No friends found</h5>
        <%= link_to  "Add new friends", users_all_path, class: "btn btn-primary" %>
    <%end%>
</div>

app/views/users/index_users.html.erb
<div class="image_cover">
    <%= image_tag  "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Casa_Classic_Cocktail_Bar_%26_Jazz_Club_by_Roland_Barrera.jpg/1280px-Casa_Classic_Cocktail_Bar_%26_Jazz_Club_by_Roland_Barrera.jpg" %>
</div>
<div class="table-scroll">
    <%if @users.length>1%>
     <div class="table-conteiner">
        <table class="table">
            <thead>
                <th colspan="1"></th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <%if current_user.is_admin?%><th scope="col">Role</th> <%end%>
                <th colspan="3"></th>
                </th>
            </thead>
            <tbody>
                <% @users.each do |user|%>
                    <%if user!=current_user&&!current_user.is_owner?&&((current_user.is_user?&&user.is_user?)||current_user.is_admin?)%>
                        <tr>
                            <td><% if user.avatar && user.avatar!="" %> 
                                    <%= image_tag  user.avatar %>
                                <% else %>
                                    <%= image_tag  "no-profile-picture.jpg" %>
                                <% end %>
                            </td>
                            <td><%= user.name %></td>
                            <td><%= user.email %> &nbsp;</td>
                            <%if current_user.is_user?%>
                                <td><%= link_to  "Add", users_all_path(id: user.id),method:"post" %>&nbsp;</td>
                            <%elsif current_user.is_admin?%>
                                <td><%if user.roles_mask==1 %> 
                                        User
                                    <%elsif user.roles_mask==2%>
                                        Owner
                                    <%else%>
                                        Admin
                                    <%end%>
                                </td>
                                <td><%= link_to  "Remove",user_path(:id=>user.id),:method => :delete, :data => {:confirm => "You sure?"},
                                        :title => "Delete #{current_user.name}",class: "btn btn-danger" %>
                            <%end%>
                        </tr>
                    <%end%>
                <% end %>
            </tbody>
        </table>
    </div>
    <%else%>
        <h1> No users found</h1>
    <%end%>
</div>

app/views/users/show.html.erb
<div class="image_cover">
    <%= image_tag  "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Casa_Classic_Cocktail_Bar_%26_Jazz_Club_by_Roland_Barrera.jpg/1280px-Casa_Classic_Cocktail_Bar_%26_Jazz_Club_by_Roland_Barrera.jpg" %>
</div>
<div class="profile">
    <div class="user_info">
        <div class="image">
            <% if current_user.avatar && current_user.avatar!="" %> 
                <%= image_tag  current_user.avatar %>
            <% else %>
                <%= image_tag  "no-profile-picture.jpg" %>
            <% end %>
        </div>
        <div>
            <strong>Name:</strong> <%= current_user.name %> 
            <br>
            <strong>Email:</strong> <%= current_user.email %>
            <br>
            <strong>Role:</strong> 
            <%if current_user.roles_mask==1 %> 
                User
            <%elsif current_user.roles_mask==2%>
                Owner
            <%else%>
                Admin
            <%end%>
        </div>
        <div>
            <%= link_to  "Edit Profile", edit_user_path, class: "btn btn-primary" %>
        </div>
        <div>
            <%= link_to  "DELETE PROFILE", user_path(:id=>current_user.id),:method => :delete, :data => {:confirm => "You sure?"},
                                        :title => "Delete #{current_user.name}",class: "btn btn-danger" %>
        </div>
    </div>
    <!--TODO aggiungi ruolo guida-->
    <%if current_user.is_user?%> 
        <div class="friend_section">
            <div class="user_add">
                <h1> Your friends</h1>
                <h5> <cite>Good friends know the exact number of drinks you can handle before you make poor choices. </cite>&#x1F609</h5>
                <%= link_to  "View friends", user_friends_path, class: "btn btn-warning" %>
            </div>
            <div class="user_add">
                <h1> Add new friends</h1>
                <h5> <cite>Good friends know the exact number of drinks you can handle before you make poor choices. </cite>&#x1F609</h5>
                <%= link_to  "Find friends", users_all_path, class: "btn btn-secondary" %>
            </div>
             <div class="user_add">
                    <h1> Your favourite Categories</h1>
                    <h5> <cite>Good friends know the exact number of drinks you can handle before you make poor choices. </cite>&#x1F609</h5>
                    <%= link_to "Your Favourite Categories", fav_categories_path, class: "btn btn-primary" %>
                    <%= link_to "Choose Your Favourite Categories", categories_path, class: "btn btn-primary" %>             </div>
        </div>
    <% end %>
    </div>