config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'

  resource :user, except: [:new]
  resolve('User') { [:user] }
  get '/users/all', to: 'users#index_users'
  get '/user/friends', to: 'users#index_friends'
  delete '/user/friends', to: 'users#remove_friend'
  post '/users/all', to: 'users#add_friend'

  #resources :sessions, only: [:create, :destroy]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get '/sessions/user', to: 'devise/sessions#create', via: :post
  end

  get '/sessions/user', to: 'devise/sessions#create', via: :post
  

  #get 'signup', to: 'users#new', as: 'signup'
  #get 'login', to: 'pages#login', as: 'login'
  #get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :categories

  get '/categories/users/fav_categories', to:'categories#fav_categories', as: 'fav_categories'
  post '/categories/users/fav_categories', to:'categories#create_fav_categories', as: 'create_fav_categories'

  resources :locations
  
  get '/locations/add_favloc/:id', to: 'locations#addto_favloc', as: 'add_favloc'
  get '/users/locations', to: 'locations#index_favloc', as: 'index_favloc'
  delete '/locations/delete_favloc/:id', to: 'locations#deletefrom_favloc', as: 'delete_favloc'

  
  resources :gatherings

  #generazione e modifica della location
  post '/gatherings/new/generate_locations', to: 'gatherings#generate_locations'
  post '/gatherings/edit/update_location', to: 'gatherings#update_location'


  get '/accept', to: 'locations#accept'
  post '/accept', to: 'locations#accept_locations'

  get '/index_admin', to: 'locations#index_admin'

  


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :types
    has_many :locations, :through => :types,  :dependent => :destroy

    has_many :fav_categories
    has_many :users, :through => :fav_categories,  :dependent => :destroy
end

#types è la tabella join location-category

app/models/fav_category.rb
class FavCategory < ApplicationRecord
    belongs_to :user 
    belongs_to :category
end

app/models/fav_location.rb
class FavLocation < ApplicationRecord
    belongs_to :user
    belongs_to :location
end

app/models/friendship.rb
class Friendship < ApplicationRecord
    belongs_to :user
    belongs_to :friend, class_name: "User" 
end

app/models/gathering.rb
class Gathering < ApplicationRecord
    belongs_to :location
    
    has_many :groups
    has_many :users, :through => :groups

    

    
end

app/models/group.rb
class Group < ApplicationRecord
    belongs_to :user
    belongs_to :gathering

end

app/models/location.rb
class Location < ApplicationRecord
    has_many :types
    has_many :categories, :through => :types,  :dependent => :destroy

    belongs_to :user


    validates_presence_of :name
    validates_presence_of :street
    validates_numericality_of :lat
    validates_numericality_of :long

    def self.search_match(partecipants)
        locations = Location.all
        matching_loc = []
        index_loc = 0
        
        locations.each do |loc|
            
            user_ok=Array.new(partecipants.length, 0)
            loc.categories.each do |cat|
                index_user = 0
                partecipants.each do |part|
                    part = User.find(part)
                    if(part.categories.include?(cat))
                        user_ok[index_user]+=1
                    end
                    index_user+=1
                end
            end
            ok=true
            user_ok.each do |like|
                if like==0
                    ok=false
                    break
                end
            end
            if(ok)
                matching_loc[index_loc]=loc
                index_loc+=1
            end
        end
        return matching_loc
    end
end

app/models/type.rb
class Type < ApplicationRecord
    belongs_to :location 
    belongs_to :category
end

app/models/user.rb
require 'rubygems'
require 'role_model'

class User < ApplicationRecord
  include RoleModel
    ROLES = %w[user owner].freeze
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  # caratteristiche di ogni utente iscritto a WhereNext:
  # autenticabili attraverso l'uso del database (la loro identità digitale
  # verrà salvata dentro il database), i loro attributi potranno essere recuperati (:recoverable), 
  # l'utente potrà clicare su "ricordami" per non dover farel'autenticazione tutte le volte (:rememberable), etc..
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, 
         :omniauth_providers => [:facebook] 

    #has_secure_password
    validates :email, presence: true, uniqueness: true

    PASSWORD_REQUIREMENTS= /\A
        (?=.{8,}) # Almeno 8 caratteri
        (?=.*\d) # Almeno un numero
        (?=.*[A-Z]) # Almeno un carattere maiuscolo
        (?=.*[[:^alnum:]]) # Almeno un simbolo
    /x

    validates :password, presence: true, format:PASSWORD_REQUIREMENTS, :if => :password
    
    has_many :fav_locations, dependent: :destroy
    has_many :locations, :through => :fav_locations, :dependent => :destroy

    has_many :my_locations, :class_name => "Location"

    has_many :fav_categories, dependent: :destroy
    has_many :categories, :through => :fav_categories, :dependent => :destroy

    has_many :friendships, dependent: :destroy
    has_many :friends, :through => :friendships

    has_many :groups, dependent: :destroy
    has_many :gatherings, :through => :groups


    roles :admin, :owner, :user

    acts_as_user :roles=> [:user, :owner, :admin]

    def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
            user.email = auth.info.email
            user.password = Devise.friendly_token[0,20]
            user.avatar = auth.info.image
            user.name = auth.info.name
            user.roles_mask = 1
        end
    end
    
    def self.new_with_session(params, session)
        super.tap do |user|
            if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
            user.email = data["email"] if user.email.blank?
            end
        end
    end 
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/gatherings_helper.rb
module GatheringsHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/type_helper.rb
module TypeHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProgLab</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "pages/nav" %>
    <%= yield %>
  </body>
</html>

app/views/pages/_home_logged.html.erb
<div class="image_cover">
    <%= image_tag  "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Casa_Classic_Cocktail_Bar_%26_Jazz_Club_by_Roland_Barrera.jpg/1280px-Casa_Classic_Cocktail_Bar_%26_Jazz_Club_by_Roland_Barrera.jpg" %>
</div>
<div class="content">
    <% if current_user.is_admin? %>
        <div class="conteiner">
            <div class="section">
                <h1> Manage Locations </h1>
                <h5> Here you can view all locations in our web site and you can edit or remove them
                </h5>
                <%= link_to  "All Locations", locations_path, class: "btn btn-warning"  %>
            </div>
            <div class="section">
                <h1> Approve Locations </h1>
                <h5> Here you can approve all pendings locations in our web site and you can approve them
                </h5>
                <%=link_to "Accept",accept_path, class: "btn btn-danger"%>
            </div>
        </div>
        <div class="conteiner">
            <div class="section">
                <h1> Manage Categories </h1>
                <h5> Here you can view all categories in our web site and you can edit or remove them
                </h5>
                <%=link_to "Categories",categories_path, class: "btn btn-danger"%>
            </div>
            <div class="section">
                <h1> Manage Users </h1>
                <h5> 
                Here you can view all users  in our web site and you can remove them
                </h5>
                <%=link_to "All Users",users_all_path, class: "btn btn-warning"%>
            </div>
        </div>
    <% elsif current_user.is_owner?  %> 
    <div class="conteiner">
            <div class="section">
                <h1> Add a Location </h1>
                <h5> Here you can request to add a location to our web site and wait for admins to approve or refuse it
                </h5>
                <%= link_to  "Insert a new location",new_location_path, class: "btn btn-warning"  %>
            </div>
            <div class="section">
                <h1> Your Locations </h1>
                <h5> Here you can view all locations that you added to our web site
                    and you can see if they have been accepted or not.<br>
                    Also you can edit them and wait for admins to approve the changes
                </h5>
                <%= link_to  "View your locations", locations_path, class: "btn btn-danger"  %>
            </div>
    </div>
     <% else %>
         <div class="conteiner">
            <div class="section">
                <h1> New Gatherings </h1>
                <h5><cite> "Everybody's got to believe in something. I believe I'll have another beer." <br> ~ W.C. Fields</cite> &#x1F919 
                </h5>
                <%= link_to  "Create a new gathering",new_gathering_path, class: "btn btn-warning"  %>
            </div>
            <div class="section">
                <h1> Your Gatherings </h1>
                <h5> <cite> "The hard part about being a bartender is figuring out who is drunk and who is just stupid." <br> ~ Richard Braunstein</cite> &#x1F64C
                </h5>
                <%= link_to  "View", gatherings_path, class: "btn btn-danger"  %>
            </div>
        </div>
        <div class="conteiner">
            <div class="section">
                <h1> See all available Locations </h1>
                <h5><cite> "The problem with the world is that everyone is a few drinks behind." <br> ~ Humphrey Bogart</cite> &#x1F919 
                </h5>
                <%= link_to  "All locations",locations_path, class: "btn btn-danger"  %>
            </div>
            <div class="section">
                <h1> Your favourite Locations </h1>
                <h5> <cite> "Alcohol may be man's worst enemy, but the bible says love your enemy." <br> ~ Frank Sinatra</cite> &#x1F64C
                </h5>
                <%= link_to  "View", index_favloc_path, class: "btn btn-warning"  %>
            </div>
        </div>
     <%end%>
</div>

app/views/pages/_home_not_logged.html.erb
<div class="image_cover">
    <%= image_tag  "pub.jpg" %>
</div>
<div class="banner">
    <div class="description">
        <h1 class="center"> This is Where Next! </h1>
        <p class="left">
            Where Next is a platform in which you can
            find common interests between you and your
            friends to organize a night out!
        </p>
        <p class="right">
            So what are you waiting for? Sign up and get ready for a fun night out with your friends</p>
    </div>
</div>

app/views/pages/_nav.html.erb
<div class="nav">
    <% if !user_signed_in? %>
        <div> <%= link_to  "Login", new_user_session_path, class: "btn btn-dark" %> </div>
        <%= link_to root_path do %>
            <%= image_tag("LogoWhereNext.png", :alt => "Where Next") %>
        <% end %>
        <div> <%= link_to  "Signup", new_user_registration_path, class: "btn btn-dark" %> </div>
    <% else%> 
        <div> <%= link_to  "Profile", user_path, class: "btn btn-dark" %> </div>
        <%= link_to root_path do %>
            <%= image_tag("LogoWhereNext.png", :alt => "Where Next") %>
        <% end %>
        <div> <%= link_to  "Logout", destroy_user_session_path, method: "DELETE", class: "btn btn-dark" %> </div>
    <% end%>
</div>

app/views/pages/home.html.erb
<% if !current_user %>
    <%= render "home_not_logged" %>
<% else%> 
    <%= render "home_logged" %>
<% end%>