config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'

  resource :user, except: [:new]
  resolve('User') { [:user] }
  get '/users/all', to: 'users#index_users'
  get '/user/friends', to: 'users#index_friends'
  delete '/user/friends', to: 'users#remove_friend'
  post '/users/all', to: 'users#add_friend'

  #resources :sessions, only: [:create, :destroy]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get '/sessions/user', to: 'devise/sessions#create', via: :post
  end

  get '/sessions/user', to: 'devise/sessions#create', via: :post
  

  #get 'signup', to: 'users#new', as: 'signup'
  #get 'login', to: 'pages#login', as: 'login'
  #get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :categories

  get '/categories/users/fav_categories', to:'categories#fav_categories', as: 'fav_categories'
  post '/categories/users/fav_categories', to:'categories#create_fav_categories', as: 'create_fav_categories'

  resources :locations
  
  get '/locations/add_favloc/:id', to: 'locations#addto_favloc', as: 'add_favloc'
  get '/users/locations', to: 'locations#index_favloc', as: 'index_favloc'
  delete '/locations/delete_favloc/:id', to: 'locations#deletefrom_favloc', as: 'delete_favloc'

  
  resources :gatherings

  #generazione e modifica della location
  post '/gatherings/new/generate_locations', to: 'gatherings#generate_locations'
  post '/gatherings/edit/update_location', to: 'gatherings#update_location'


  get '/accept', to: 'locations#accept'
  post '/accept', to: 'locations#accept_locations'

  get '/index_admin', to: 'locations#index_admin'

  


end

app/models/location.rb
class Location < ApplicationRecord
    has_many :types
    has_many :categories, :through => :types,  :dependent => :destroy

    belongs_to :user


    validates_presence_of :name
    validates_presence_of :street
    validates_numericality_of :lat
    validates_numericality_of :long

    def self.search_match(partecipants)
        locations = Location.all
        matching_loc = []
        index_loc = 0
        
        locations.each do |loc|
            
            user_ok=Array.new(partecipants.length, 0)
            loc.categories.each do |cat|
                index_user = 0
                partecipants.each do |part|
                    part = User.find(part)
                    if(part.categories.include?(cat))
                        user_ok[index_user]+=1
                    end
                    index_user+=1
                end
            end
            ok=true
            user_ok.each do |like|
                if like==0
                    ok=false
                    break
                end
            end
            if(ok)
                matching_loc[index_loc]=loc
                index_loc+=1
            end
        end
        return matching_loc
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    before_action :authenticate_user!
    load_and_authorize_resource
    def index_admin
        if current_user.is_admin?
            @locat = Location.all
        else 
            redirect_to locations_path
        end
    end

    def index
        if current_user.is_owner?
            @location= current_user.my_locations
        elsif current_user.is_user?
            @location = Location.where(status: "accepted")
        else 
            @location = Location.all
        end
    end

    def new 
        @newLoc = Location.new
        authorize! :create, @newLoc, :message=>"You are not authorized to complete this action."
        @categories = Category.all
        @noCats = "Non ci sono categorie disponibili"
    end

    def show
        if current_user.is_admin? || current_user.is_owner?
            @location = Location.find(params[:id])
        else 
            @location = Location.where(status: "accepted", id: params[:id])[0]
        end
        
        @cats = []
        if @location != nil
            @location.categories.each do |c|
                @cats.append(Category.find(c.id))
            end
        end
    end 

    def create
        if  !Location.where(name: params[:locations][:name], name: params[:locations][:lat], name: params[:locations][:long] ).empty?
            render html: "Il locale che stai cercango di aggiungere gia' esiste"
            
        else 

            @client = OpenStreetMap::Client.new
            @loc = "#{params[:locations][:street]}/" << "/#{params[:locations][:city]}"
            @res=@client.search(q: @loc, format: 'json', addressdetails: '1', accept_language: 'it')
            @lat=@res[0]['lat']
            @long=@res[0]['lon']
        
            @newLoc = Location.new(params.require(:locations).permit(:name, :foto))
            authorize! :create, @newLoc, :message=>"You are not authorized to complete this action."
            @newLoc.lat=@lat
            @newLoc.long=@long
            @newLoc.street="#{params[:locations][:street]}, " << "#{params[:locations][:city]}"
            @newLoc.user= current_user
            @newLoc.update_attributes(status: "pending")
            @newLoc.user=current_user
            @array = params[:categ]
            if @array != nil
                @arr = []
                @array.each do |c|
                    @arr.append(Category.find(c))
                end
                @newLoc.categories = @arr
            end

            @newLoc.user = current_user
            
            @newLoc.save
            
            redirect_to locations_path  
         end
    end

    #Manca autenticazione admin
    #Devi passare un array che contiene l-id di location e l-id di category 
    #cosi lo cerchi dentro type e se non esiste la categoria indicata dentro type,  vuol dire 
    #che il locale indicato non gli appartiene e quindi aggiungi la tupla. 
    def edit   
        @update_loc = Location.find(params[:id])
        authorize! :update, @update_loc, :message=>"You are not authorized to complete this action."
        @cats = @update_loc.categories
        @categories = Category.all
        @status_array = ["accepted", "pending", "rejected"]
    end 

    #Manca autenticazione admin
    def destroy 
            id = params[:id]
            @location = Location.find(id) 
            authorize! :destroy, @location, :message=>"You are not authorized to complete this action."     
            @location.destroy
            redirect_to locations_path
    end

    #Manca autenticazione admin
    def update
        @update_loc = Location.where(id: params[:id]).first
        authorize! :update, @update_loc, :message=>"You are not authorized to complete this action."
        if current_user.is_admin?
            @update_loc.update_attributes(status: params[:status])
        else  
            @update_loc.update_attributes(name: params[:locations][:name], foto: params[:locations][:foto])
            @allCats = params[:categ]
            if @allCats != nil
                @tmp = []
                @allCats.each do |c|
                    @tmp.append(Category.find(c))
                end
                @update_loc.categories = @tmp
            end
        end  
        redirect_to location_path(@update_loc)
    end

    def accept
        @list = Location.where(status: "pending")
        @noList = "Non ci sono locali da accettare"
    end

    def accept_locations
        @list = Location.where(status: "pending")
        @accept = params[:accepted]
        if @list != nil 
            @list.each do |nl|
                @n = Location.find(nl.id)
                @n.update_attributes(status: "rejected")
                
            end
            if @accept != nil 
                @accept.each do |al|
                    @a = Location.find(al)
                    #render html: @a
                    @a[0].update_attributes(status: "accepted")
                end
            end
        end
        redirect_to locations_path
    end

    def addto_favloc
        if current_user.is_user?
            id = params[:id]
            @loc = Location.find(id)
            if(!current_user.locations.include?(@loc))
                current_user.locations << @loc
            end
        end
        redirect_to index_favloc_path
    end

    def deletefrom_favloc
        id = params[:id]
        @loc=Location.find(id)
        if(current_user.locations.include?(@loc))
            current_user.locations.delete(@loc)
        end
        redirect_to request.referrer
    end

    def index_favloc
        if current_user.is_user?
            @locations=current_user.locations
        else 
            redirect_to root_path
        end
    end

end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/accept.html.erb
<div class="image_cover">
    <%= image_tag  "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Casa_Classic_Cocktail_Bar_%26_Jazz_Club_by_Roland_Barrera.jpg/1280px-Casa_Classic_Cocktail_Bar_%26_Jazz_Club_by_Roland_Barrera.jpg" %>
</div>
<div class="table-scroll">
  <div class="title"><h1>Accept Locations</h1> </div>
  <%= form_tag '/accept', :action => 'accept_locations', :method =>'POST' do %>
  <div class="table-conteiner">
    <% if !@list.empty? %>
      <table class="table">
          <thead>
              <th>Nome</th>
              <th>Long</th>
              <th>Lat</th>
              <th> Select which accept </th>
              <th colspan="3"></th>
          </thead>
          <tbody>
              <% @list.each do |loc| %>
                  <tr>
                      <td><%= loc.name %></td>
                      <td><%= loc.long %></td>
                      <td><%= loc.lat %> &nbsp;</td>
                      <td><%= check_box_tag "accepted[#{loc.id}]", loc.id -%><td>
                      <td><%= link_to "Show", location_path(loc.id) %>&nbsp;</td>
                  </tr>
              <% end %>
          </tbody>
      </table>
    </div>
    <% else %>
      There aren't locations to accept
    <%end%>
    <% if !@list.empty? %>
    <%= submit_tag "Confirm", class: "btn btn-success"%>
    <%end%>
  <% end -%>
</div>

app/views/locations/edit.html.erb
<div class="image_cover">
    <%= image_tag  "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Casa_Classic_Cocktail_Bar_%26_Jazz_Club_by_Roland_Barrera.jpg/1280px-Casa_Classic_Cocktail_Bar_%26_Jazz_Club_by_Roland_Barrera.jpg" %>
</div>
<div class="table-scroll">
  <h1>Edit: <%=@update_loc.name%> </h1>

  <%= form_tag :location, :url => {:action => 'update', :id => @update_loc.id},
    :method => 'put' do %>
    <div>
      <%if current_user.is_owner?%>
        <div class="list">
          <p><label for="name">Name of location:</label>

          <%= text_field 'locations', 'name' , value: @update_loc.name%></p>

          <p><label for = "lat">Link Photo</label>:

          <%= text_field 'locations', 'foto',  value: @update_loc.foto %></p>
        </div>
        <div class="list">
          <h5> Category:</h5>
          <%if !@categories.empty?%>
            <div class="table-conteiner list">
            <ul>
              <% @categories.each do |cat| %>
                  <li>
                    <% if @cats.include? cat %>
                      <%= check_box_tag 'categ[]', cat.id, true %>
                      <%=  cat.name %>
                    <% else %>
                      <%= check_box_tag 'categ[]', cat.id %>
                      <%=  cat.name %>
                    <% end %>
                  </li>
              <% end %>
            </ul>
            </div>
          <%else%>
            <h3>There aren't category yet</h3>
          <%end%>
        </div>
    </div>
    <%end%>
    <%if current_user.is_admin?%>
      <div>
        <h4>Status:</h4>
          <% @status_array.each do |s| %>
            <% if s == @update_loc.status %>
                <%= radio_button_tag(:status, s, true)%>
            <% else %>
                <%= radio_button_tag(:status, s)%>
            <% end %>
            <%= s %>
      <% end %>
      </div>
  
  </div>
  <%end%>
  <%= submit_tag "Update", class:"btn btn-primary" %>
  <% end -%>
</div>

app/views/locations/index.html.erb
<div class="image_cover">
    <%= image_tag  "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Casa_Classic_Cocktail_Bar_%26_Jazz_Club_by_Roland_Barrera.jpg/1280px-Casa_Classic_Cocktail_Bar_%26_Jazz_Club_by_Roland_Barrera.jpg" %>
</div>
<div class="table-scroll">
    <div class="title">
        <h1> Locations </h1>
    </div>
    <div class="table-conteiner">
        <table class="table">
            <thead>
                <tr>
                <th scope="col">Name</th>
                <th scope="col">Street</th>
                <%if !current_user.is_user?%> <th scope="col">Status</th> <%end%>
                <th colspan="5"></th>
            </thead>
            <tbody>
                <% @location.each do |loc| %>
                    <tr>
                        <td><%= loc.name %></td>
                        <td><%= loc.street %> &nbsp;</td>
                        <%if !current_user.is_user?%><td><%= loc.status %> &nbsp;</td> <%end%>
                        <td><%= link_to "Show", location_path(loc.id) %>&nbsp;</td>
                        <%if !current_user.is_user?%><td><%= link_to "Edit", edit_location_path(loc.id) %>&nbsp;</td><%end%>
                        <%if current_user.is_admin?%><td><%= link_to "Destroy", loc, method: :delete, data: { confirm: "Are you sure?" } %>&nbsp;</td><%end%>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
    <%if current_user.is_owner?%>
        <%=link_to "New", new_location_path, class: "btn btn-primary"%>
    <% elsif current_user.is_admin?%>
        <%=link_to "Accept new Locations",accept_path, class: "btn btn-primary"%>
    <%end%> 
</div>

app/views/locations/index_favloc.html.erb
<div class="image_cover">
    <%= image_tag  "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Casa_Classic_Cocktail_Bar_%26_Jazz_Club_by_Roland_Barrera.jpg/1280px-Casa_Classic_Cocktail_Bar_%26_Jazz_Club_by_Roland_Barrera.jpg" %>
</div>
<div class="table-scroll">
    <div class="title">
        <h1> Your Favourites Locations </h1>
    </div>
    <%if !@locations.empty?%>
        <div class="table-conteiner">
            <table class="table">
                <thead>
                    <th scope="col">Name</th>
                    <th scope="col">Street</th>
                    <th colspan="3"></th>
                    </th>
                </thead>
                <tbody>
                    <% @locations.each do |loc| %>
                        <tr>
                            <td><%= loc.name %></td>
                            <td><%= loc.street %></td>
            
                            <td><%= link_to "Show", location_path(loc.id) %>&nbsp;</td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    <%else%>
        You haven't favourites locations yet
    <%end%>
</div>

app/views/locations/new.html.erb
<div class="image_cover">
    <%= image_tag  "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Casa_Classic_Cocktail_Bar_%26_Jazz_Club_by_Roland_Barrera.jpg/1280px-Casa_Classic_Cocktail_Bar_%26_Jazz_Club_by_Roland_Barrera.jpg" %>
</div>
<%= link_to 'Back', :back, class:"btn btn-back" %>
<div class="table-scroll">
  <h1>Add a location</h1>

  <%= form_tag :action => 'create' do %>
  <p><label for="name"><strong>Name of location:</strong></label>

  <%= text_field 'locations', 'name', required: true%></p>

  <!-- l'utente inserisce la via del locale, la città e il paese e Open Street Map trova long e lat-->

  <p>
    <label for="street"><strong>Street:</strong></label>
    <%= text_field 'locations','street',required: true%>
    <label for="city"><strong>City:</strong></label>
    <%= text_field 'locations','city',required: true%>

  </p>

  <p><label for = "foto"><strong>Link Photo</strong></label>:

  <%= text_field 'locations', 'foto' %></p>

  <h5><label for = 'cat'><STRONG>Select category:</label></strong> </h5>
  <div class="table-conteiner">
    <ul>
      <% if !@categories.empty? %>
        <% @categories.each do |cat| %>
            <li>
              <%=  cat.name -%>
              <%= check_box_tag 'categ[]', cat.id -%>
            </li>
        <% end %>
      <% else %>
        <br/>
        <%= @noCats %>
      <%end%>
    </ul>
  </div>

  <%= submit_tag "Create",class:"btn btn-primary" %>
  <% end -%>
</div>

app/views/locations/show.html.erb
<div class="image_cover">
    <%= image_tag  "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Casa_Classic_Cocktail_Bar_%26_Jazz_Club_by_Roland_Barrera.jpg/1280px-Casa_Classic_Cocktail_Bar_%26_Jazz_Club_by_Roland_Barrera.jpg" %>
</div>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
   integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
   crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
   integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="
   crossorigin=""></script>
<div class="table-scroll">
  <h1><%= @location.name %></h1>
  <p>Owner: <%if @location.user==current_user%> You <%else%> <%=@location.user.name%> <%end%> </p>
  <%if !@cats.empty?%>
    <p>Category: <br>
      <% @cats.each do |c| %>
        <%= link_to  c.name, c %> 
      <% end %>
    </p>
  <%end%>
    <div id="mapid" style="height:180px">
    </div>
    <script> 
      var mymap = L.map('mapid').setView(['<%=@location.lat %>','<%=@location.long %>'], 13);
      L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(mymap);
    L.marker(['<%=@location.lat %>','<%=@location.long %>']).addTo(mymap)
      .bindPopup('<%=@location.street %>')
      .openPopup();
    </script>
  </p>

  <!-- TODO ruoli-->
  <%if current_user.is_user?%>
  <%if !current_user.locations.include?(@location)%>
    <%= link_to add_favloc_path(@location.id), id:"heart" do %>
      <svg  xmlns="http://www.w3.org/2000/svg" viewBox="0 0 446.2 446.2"><path d="M223.6 410.4c-3.7 0-7.8-1.6-11-4.2L37.1 239.5C13.6 216.6 0 186.8 0 154.9s13.1-62.2 37.1-84.6c48.6-46 127.5-46 176.1 0l9.9 9.4 9.9-9.4c48.6-46 127.5-46 176.1 0l0 0c24 22.5 37.1 52.8 37.1 84.6s-13.1 62.2-37.1 84.6L234.6 406.2C231.4 408.8 227.3 410.4 223.6 410.4zM125.4 66.6c-24 0-48.1 8.9-66.4 26.1 -17.8 16.7-27.2 38.7-27.2 62.2s9.9 45.5 27.2 62.2L223.6 373.3 388.2 217.1c17.8-16.7 27.2-38.7 27.2-62.2s-9.9-45.5-27.2-62.2l0 0c-36.6-35-96.1-35-133.2 0l-20.9 19.9c-6.3 5.7-15.7 5.7-21.4 0l-20.9-19.9C173.5 75 149.4 66.6 125.4 66.6z" fill="#1185E0"/></svg>
    <%end%>
    <%else%>
    <%= link_to delete_favloc_path(@location.id), method: :delete do%>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 447.2 447.2"><path d="M410.1 70.5c-48.6-46-127.5-46-176.1 0l-10.4 9.9 -9.9-9.4c-48.6-46-127.5-46-176.1 0C13.6 93.5 0 123.3 0 155.7c0 31.9 13.1 62.2 37.1 84.6l175.5 166.7c3.1 2.6 6.8 4.2 11 4.2 4.2 0 7.8-1.6 11-4.2l175.5-166.7c24-22.5 37.1-52.8 37.1-84.6C447.2 123.3 433.6 93.5 410.1 70.5z" fill="#4DCFE0"/></svg>
    <%end%>
  <%end%>
  <%end%>
</div>